name: Build and package theme

on:
  push:
    branches:
      - main
      - refactor_comment
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install pnpm -g

      - name: Build TypeScript files
        run: |
          pnpm install
          echo "NO_DEPS_HOIST=true" >> $GITHUB_ENV
          pnpm build

      - name: Create ZIP package
        run: zip -r shokaX.zip * -x 'scripts/*.ts' 'source/tsconfig.json' 'scripts/tsconfig.json' '*.tsbuildinfo' "node_modules/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shokaX-stable
          path: shokaX.zip