name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # 根据你的需求设置 Node.js 版本

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-theme-particles hexo-renderer-inferno  # 安装主题和依赖

      - name: Generate static files
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public